### PR TITLE
Adding new features and change styles

### PR DESCRIPTION
**Pull request by athif23**
### 1. Install `inquirer`, `chalk`, and `colors`'s NPM packages.
I install **inquirer** for adding cool things to the CLI (you can see what the cool things are in [here](https://github.com/SBoudrias/Inquirer.js/)), while **colors** so we can style the output in the CLI. I know there's already **chalk** in the code but I think @Leoat12 forget to add it to the **package.json** (or maybe it's just me) when he makes this repository, so I add it and install it.

### 2. Add `clearArticles`'s feature.
I know there's already **Delete Article**'s feature in the app but the thing is, what if we want to remove all the articles without having to write `to-read deleteArticle <id>` multiple times? So, I added this just to make it easy to clear all articles or more precisely, to clear the storage.

### 3. Add message when there are no articles in the storage.
When we run this `to-read list` but there are no articles in the storage, it will output this: 

			There's no article you saved.

### 4. Add `opens`'s feature.
This is the cool things I talked about at the beginning. So, I use `inquirer` to make the app more interactive. With, this feature, now we can open each article by selecting it without having to type the article's id or even remember it.

### 5. Change the style of the output.
I'm using `colors` to do this.

### Future Planning
- Make the delete's version of `opens`. So, we can delete by selecting it or we can delete all at once.

### A few questions to @Leoat12 
- Can we just delete `chalk` and just using `colors`? Because(in my experience) `chalk` can't work in my Git Bash. Or, maybe it's just me.
- I don't really understand this status thing. Can you kindly explain to me, how it will work or what it will do? 

#### Thanks and sorry if there are changes that do not match your preferences. I'm still learning too.

### CODE REVIEW

**Comment by Leoat12** [comment]
Thank you for the contribution. It is huge! 

While I was testing the new features I was not able to use the "ops" feature. The list appears and I select the articles I want to open and press Enter, but nothing happens besides appearing the options I selected  and. Screenshots below.
capture
capture2

Any idea of what is happening?

Answering the questions: 
- You can change `chalk` for `colors`, just make sure all display related stuff is in the Display class. Some things remains in the Action class because I didn't finish the transfer, but the idea is everything related to printing must be in the Display class. 
- The status of the article? It is just a management feature for the user, similar to todo lists where there is status like "To do", "Doing" and "Done" the same thing would apply here. 

Feel free to ask any questions and change anything, no need to apologize for it. hahaha

We just have to find out why the "ops" command is not working properly here and then I will merge. :)

**Comment by athif23** [comment]
Hmm. That's weird. 
I will see if there's some mistakes or errors in the code.  

And, thanks for the answers.

**Comment by athif23** [comment]
### **Fixed.**
#### The problems are...
Wait before that see this first:

			name: article.title + " -> " + colors.blue.bold(article.url)

and here:

		.then((answers) => {
			const value = Object.values(answers);
            const arrVal = Object.values(value[0]);
			const art = articles.filter((val, i) => { 
					return val.title === arrVal[i]; 
			});

			art.forEach(v => opn(v.url));

#### Now, did you see the problem? Yeah, the return statement in `.filter` is the mistake here. Because it's same like this:
		
			return "title" === "title -> http://url.com/"

The `.filter` will always return nothing to the `art` variable because I compare two things that completely different. So here, what I change it to be:

		.then((answers) => {
			const value = Object.values(answers);
            const arrVal = Object.values(value[0]);
			const art = articles.filter((article, i) => { 
					const toStr: String = arrVal[i].toString();
					const splitStr = toStr.split(" -> ");
					return article.title === splitStr[0];
			});

			art.forEach(v => opn(v.url));

So, I convert (because it says that it's object type) to a string. Then, I split it with `" -> "` so it will be an array of two string. And, I just need to compare the first index in the array with `article.title`. Done.

**I already test it**, and it works fine. And, I hope it works fine on other computers too.

**Thanks.**

**Comment by Leoat12** [comment]
Everything working fine here! Merged!
Thanks again, it would take a long time for me to realize such features were so convenient!

**Comment by athif23** [comment]
Oh, that's great. But, I just realize, I make some mistake in the docs. We have to `npm run build` first before we run `npm install -g ./` to install the app. 

I think we need to add that in the docs. So it will not confuse someone later. Or, can we actually run the app without it? What do you think?

**Pull request merged**
