### PR TITLE
Add delete selected article's feature and reformat the docs

### PR DESCRIPTION
**Pull request by athif23**
I will just keep this short.

## 1. Delete selected articles
While it's maybe not really great and almost the same with opens. It's pretty much working fine. But, I'm not really satisfied with the result.

## 2. Reformat the docs
So, what I am doing here is just make the docs to be more short by making a separate file for actions' documentation.

That's it, you can see it on your own and check the feature. And give me feedback if there's some mistakes or errors in the code or documentation.

Thanks.

### CODE REVIEW

**Comment by Leoat12** [comment]
I was not able to test the feature because there are conflicts that must be solved, but I'm sure the delete selected articles features will have the same bug as the open the selected articles feature. 
The `deleteAll` method you included has this:
```typescript
.then(answers => {
                    const value = Object.values(answers);
                    const arrVal = Object.values(value[0]);
                    const art = articles.filter((article, i) => {
                        const toStr: String = arrVal[i].toString();
                        const splitStr = toStr.split(" -> ");
                        return article.title === splitStr[0];
                    });
                    this.storage.deleteAll(art);
                });
```
Because the `filter` function uses the index from `articles` array, the `arrVal` constant must be the same size as the `articles` array otherwise it will cause a `cannot call toString of undefined` in this line: `const toStr: String = arrVal[i].toString();`, I solved this on my latest commit like this:

```typescript
.then(answers => {
                    const value = Object.values(answers);
                    const arrVal : string[] = Object.values(value[0]);
                    let titles: string[] = [];
                    arrVal.forEach(ar => {
                        titles.push(ar.split(" -> ")[0])
                    });
                    const art = articles.filter((article, i) => {
                        return titles.includes(article.title);
                    });
                    art.forEach(article => {
                        opn(article.url);
                    });
                });
```
Can you see the difference?

So, test the `deleteAll` method as I described and make sure it is working as expected, that the user will not be required to delete all articles, not only the ones he selected. 

To do that, also solve the conflicts with the latest commits. Feel free to ask any questions.

**Comment by athif23** [comment]
I will do that but maybe it will take a couple of hours to resolve this.

Anyway, Thanks.

**Comment by athif23** [comment]
Done. Can you review it? Maybe, there's something I forget to fix.

**Comment by Leoat12** [comment]
Everything looks perfect! Thanks for this contribution once more! :D
It has been incredible to work with you. Let's continue pushing forward!

**Pull request merged**
